### ISSUE TITLE
itch.io PC app invalid game error when trying to install passworded game

### ISSUE THREAD

**Issue by badon** [itchio/itch.io#802] opened 2018-03-08 08:38 UTC
I used the passworded URL from email in the itch.io PC app, then clicked the install button for Spacebase 19, and I got the error in the screenshot.

![itch io pc app invalid game error during install 2018-03-08-thu-00-29-06 image 2](https://user-images.githubusercontent.com/5954485/37141075-c389b600-2268-11e8-9817-8d87ebea7f31.png)

**Comment by morgondag** [comment] 2018-03-08 09:17
might be the spacebase 19 guys(me) fault as the application is zipped. 
Does the desktop app support zipped targets?

**Comment by fasterthanlime** [comment] 2018-03-08 09:20
> might be the spacebase 19 guys(me) fault as the application is zipped.
> Does the desktop app support zipped targets?

The app supports that and a lot of other build configurations: https://itch.io/docs/itch/integrating/quickstart.html

However, restricted games are not handled properly by the current version of the app: https://github.com/itchio/itch/issues/1080

(Closing as this is a duplicate of the itchio/itch issue).

**Closed by fasterthanlime** 2018-03-08 09:20 UTC
