### ISSUE TITLE
"download bundle" page not allowing to download bundle

### ISSUE THREAD

**Issue by tuxun** [itchio/itch.io#1096] opened 2020-07-17 09:33 UTC
Hi, i bought my first bundle and i cant download it.
Indeed, the download bundle page does not allow us to download the bundle all at once.
We have to parse only 59 pages of 10 games each, for download every version per Operating system we use.

3*59*10= 1770 pages to visit for download the bundle I paid. 
Please put a torrent link in the bundle page.

**Comment by tuxun** [comment] 2020-07-17 09:34
pff markdown of gh sucks

**Comment by fasterthanlime** [comment] 2020-07-17 10:38
Closing as duplicate of https://github.com/itchio/itch.io/issues/1086

I'm sorry this angers you, but you can download everything you bought - there's no issue here.

**Closed by fasterthanlime** 2020-07-17 10:38 UTC
