### ISSUE TITLE
Embed payment flow doesn't work on mobile Safari / Chrome, from european IPs

### ISSUE THREAD

**Issue by fasterthanlime** [itchio/itch.io#369] opened 2016-03-12 14:11 UTC
Steps to reproduce:

  * Visit http://earthfallgame.com/ from mobile Safari or mobile Chrome
  * click 'Buy now'
  * click 'Paypal'
  * MOSS form opens in new tab, fill it out
  * Tax preview shows up in same tab, click 'Continue payment'

What happens:

  * On Chrome, Paypal is opened in a tab, then the tax preview tab is closed, which brings the user back to the original page (the one containing the embed widget)
  * Safari doesn't even seem to bother opening the Paypal tab and just brings the user back to the original page directly.

**Comment by leafo** [comment] 2016-03-12 19:24
Should be fixed now!

**Closed by leafo** 2016-03-12 19:24 UTC
Labels: bug

**Comment by Glanzer** [comment] 2017-08-03 14:51
I am experiencing a similar problem. The payment process seems to run like it's intended, but paypal allegedly can't complete my transaction.

It seems the problem is occurring with paypal, but the same style of payment works flawlessly from other services.

- Problem occurs with Chromium, Chrome, Firefox and Epiphany.
- I live in the EU and I'm on Linux
- I have tried buying [Hylics](https://mason-lindroth.itch.io/hylics) and [Mewnbase](https://cairn4.itch.io/mewnbase)
- I don't own a credit-card, and paypal automatically charges my giro, which usually works fine
- Payment worked previously with ebay, shapeways; bandcamp, googleplay, steam and gog (and still does). I would have contacted their support if the error wasn't (as far as I've tried) exclusive to itch.io.
- I have "tried again later", the way paypal advised me to, with no effect.
- I have deleted all cookies and "tried again later" as well.
- I also compared (and corrected) my paypal and itch.io billing addresses to avoid errors there.

Screenshot for completeness:
![screenshot from 2017-08-03 16-31-01](https://user-images.githubusercontent.com/7443968/28926930-8a4043ea-7869-11e7-8855-d505c6e7c77c.png)
