### ISSUE TITLE
Tyranobuilder games cannot be launched directly from itch.io app

### ISSUE THREAD

**Issue by triptych** [itchio/itch.io#588] opened 2017-01-09 01:01 UTC
For context:

Tyranobuilder forum post
http://steamcommunity.com/app/345370/discussions/1/142261027576004322/

Itch.io post
https://itch.io/post/95334

It looks like when I try to launch a game created with Tyranobuilder, that the .exe does not have the folder context so it is unable to find the data files it needs in order to run. If you run the .exe in the right folder it works, but you cannot launch the game from inside the itch.io app.

**Comment by fasterthanlime** [comment] 2017-01-09 17:13
I replied on the itch.io post!

**Comment by fasterthanlime** [comment] 2017-01-10 12:24
Closing as duplicate of https://github.com/itchio/itch/issues/1092 - will fix soon!

**Closed by fasterthanlime** 2017-01-10 12:24 UTC
