### ISSUE TITLE
PC software broken with misconfigured hidden CAPTCHA's blocking embedded files from static.itch.io CDN

### ISSUE THREAD

**Issue by badon** [itchio/itch.io#766] opened 2017-12-13 09:01 UTC
![itch io pc software hidden captcha s 2017-12-13-wed-00-57-51](https://user-images.githubusercontent.com/5954485/33930165-d6aeeda0-dfa0-11e7-9f79-ad7461ce4e77.png)

See also this bug report, it's the exact same problem, just with the CAPTCHA's infesting the PC software, which the stupidest place in the world to put CAPTCHA's. Once again, somebody put CAPTCHA's everywhere without testing them. Somebody needs to get yelled-at.

https://github.com/itchio/itch.io/issues/765

**Comment by leafo** [comment] 2017-12-13 17:00
There is no capatcha on that domain, what did you see that made you think there was?

**Comment by leafo** [comment] 2017-12-13 17:01
Closing this since it's a duplicate of #764, I see now that you're having trouble with cloudflare.

**Closed by leafo** 2017-12-13 17:01 UTC
