### ISSUE TITLE
changing my GitHub username resulted in my itch.io account becoming inaccessible. can something be done so access isn't based on the username?

### ISSUE THREAD

**Issue by karl01101101** [itchio/itch.io#1059] opened 2020-04-04 16:39 UTC

**Comment by fasterthanlime** [comment] 2020-04-04 16:43
Seems like a duplicate of https://github.com/itchio/itch.io/issues/1057 - there's been issues with "login through GitHub" for a little while now, very probably unrelated to your username change.

**Closed by fasterthanlime** 2020-04-04 16:43 UTC
