### ISSUE TITLE
Itch.io app updates corrupted for Dicey Dungeons

### ISSUE THREAD

**Issue by TerryCavanagh** [itchio/itch.io#941] opened 2019-01-09 18:03 UTC
Hello! When some users updated my game Dicey Dungeons from v0.14 to v0.15 on windows, they got this error message, which is Dicey Dungeons specific:

`bad node type, expected element but found 6`

It turned out to be an XML parsing error, caused by a corrupted XML file. This seemed to only affect users using the itch.io app.

It seems like, somehow, the itch.io app was downloading a broken update that wouldn't start. This happened twice: one set of users reported it when updating from v0.14 to v0.15. Another when updating from v0.15 to v0.15.1. For v0.15 and before, I updated the game using the website. For v0.15.1, I've started using butler.

The fix was to delete the game and reinstall it on the itch.io app.

(If you need any more information about this, let me know!)

**Comment by fasterthanlime** [comment] 2019-01-09 19:01
Hey Terry, thanks for the detailed report, I'll take a look at it tomorrow.

**Comment by fasterthanlime** [comment] 2019-01-09 19:46
@TerryCavanagh Do you happen to have the v0.14 and v0.15 build zips somewhere? If so, uploading them to a restricted itch.io page and sending me the URL would be great!

(you can DM me the URL on twitter if you don't want to post it here - shouldn't matter tbh because only you & admins will be able to see the page)

**Comment by fasterthanlime** [comment] 2019-01-10 02:31
> Do you happen to have the v0.14 and v0.15 build zips somewhere?

Nevermind that request - I'm now curious to see what exactly the invalid files looked like on disk

**Comment by fasterthanlime** [comment] 2019-01-10 02:56
> Nevermind that request - I'm now curious to see what exactly the invalid files looked like on disk

Nevermind that request either, I have found the issue, and am working on a fix.

Closing as duplicate of https://github.com/itchio/itch/issues/2230

**Closed by fasterthanlime** 2019-01-10 02:56 UTC
