### ISSUE TITLE
Butler status has blank fields

### ISSUE THREAD

**Issue by neauoire** [itchio/itch.io#837] opened 2018-05-24 21:30 UTC
For the past few days, the butler manages to get builds uploaded, but returns no build numbers nor statuses.

<img width="584" alt="screen shot 2018-05-25 at 9 28 24 am" src="https://user-images.githubusercontent.com/1455726/40514690-39f72bba-5ffe-11e8-9e79-d2fad7f0db66.png">

**Comment by fasterthanlime** [comment] 2018-05-24 22:04
Thanks for the report.

I see the issue, it's been caused by an API change. We'll be rolling out a fix shortly!

**Comment by fasterthanlime** [comment] 2018-05-25 09:44
A fix has been deployed

![image](https://user-images.githubusercontent.com/7998310/40538073-eb34f71a-6010-11e8-862c-ea73176d0f1c.png)

(It's a server-side fix, you don't need to upgrade butler)

**Closed by fasterthanlime** 2018-05-25 09:44 UTC
